flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: e2e-tests
      paths: 
      - e2e-tests
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: unit-tests
      paths: 
      - unit-tests
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: my_component_1  # this is an identifier that should not be changed
      name: my_component_1  # this is a display name, and can be changed freely
      paths:
        - flag_coverage_filtering/lib.py
    - component_id: my_component_2
      name: my_component_2
      paths:
        - flag_coverage_filtering/lib2.py
