name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        pip install codecov
        
    - name: Run e2e tests with coverage
      run: |
        pytest e2e-tests --cov=flag_coverage_filtering --cov-report=xml
        
    - name: Upload e2e coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: suejung-sentry/flag-coverage-filtering
        flags: e2e-tests

    # - name: Run unit tests with coverage
    #   run: |
    #     pytest unit-tests --cov=flag_coverage_filtering --cov-report=xml
        
    # - name: Upload unit coverage reports to Codecov
    #   uses: codecov/codecov-action@v5
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     slug: suejung-sentry/flag-coverage-filtering
    #     flags: unit-tests
